apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tengine
  labels:
    app: tengine
spec:
  replicas: 1
  template:
    metadata:
      name: tengine
      labels:
        app: tengine
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["/bin/sh", "-c"],
            "args": ["mkdir -p /tmp/nginx"],
            "volumeMounts": [
              {
                "name": "log",
                "mountPath": "/tmp"
              }
            ]
          }
        ]'
    spec:
      volumes:
      - name: log
        emptyDir: {}
      - name: nginx-conf
        nfs:
          server: 192.168.8.19
          path: /mnt/fs/nfs/config/nginx/conf.d/
      containers:
      - name: nginx
        image: registry.cn-hangzhou.aliyuncs.com/ng_containers/tengine:2.1.3
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: log
          mountPath: /var/log
        resources:
          limits:
            cpu: 2000m
      - name: fluentd
        image: registry.cn-hangzhou.aliyuncs.com/ng_containers/fluentd:latest
        imagePullPolicy: Always
        env:
        - name: ES_HOST
          value: elasticsearch.kube-system
        - name: ES_PORT
          value: "9200"
        volumeMounts:
        - name: log
          mountPath: /var/log
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 1000m
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: tengine
  name: tengine
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: tengine
#  sessionAffinity: ClientIP