kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elasticsearch
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: elasticsearch
        image: elasticsearch:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 9200
        - name: cluster
          containerPort: 9300
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elasticsearch
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 9200
    targetPort: api
    protocol: TCP
  selector:
    app: elasticsearch

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: kibana
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kibana
        image: kibana:5.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: ui
          containerPort: 5601
          protocol: TCP
        args:
        - -e
        - 'http://elasticsearch:9200'
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m

---
kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: kibana
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: ui
    protocol: TCP
  selector:
    app: kibana