apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-system
  labels:
    task: monitoring
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        app: grafana
    spec:
      volumes:
      - name: config
        hostPath:
          path: /var/lib/grafana
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: secret
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_FROM_ADDRESS
          value: notify@inspireso.org
        - name: GF_SMTP_HOST
          value: smtp.inspireso.org:25
        - name: GF_SMTP_USER
          value: notify@inspireso.org
        - name: GF_SMTP_PASSWORD
          value: Mail@2016
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    app: grafana
    kubernetes.io/cluster-service: "true"
  name: grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana