apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      nodeSelector:
        kubernetes.io/hostname: kuben0
      volumes:
        - name: grafana-storage
          hostPath:
            path: /var/lib/grafna
        - name: grafana-config
          emptyDir: {}
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
              - name: api
                containerPort: 3000          
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: secret
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage

---
apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: grafana