kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: kube-system
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  selector:
    matchLabels:
      type: nfs
      path: kube-system
      mode: rw

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: default
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  selector:
    matchLabels:
      type: nfs
      path: default
      mode: rw

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: devops
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  selector:
    matchLabels:
      type: nfs
      path: devops
      mode: rw