kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      volumes:
      - name: data
#        hostPath:
#          path: /var/lib/jenkins
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: jenkins
        image: registry.cn-hangzhou.aliyuncs.com/base_containers/jenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/jenkins_home
          subPath: jenkins
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 2Gi

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins

spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: cluster
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins