kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  labels:
    type: nfs
    mode: rw
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 150Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.8.19
    path: /mnt/fs/nfs/data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  labels:
    type: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  selector:
    matchLabels:
      type: nfs
      mode: rw