apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: registry.cn-hangzhou.aliyuncs.com/base_containers/alpine-box:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always