kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jenkins
  namespace: dev
  labels:
    app: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: jenkins
        image: jenkins:2.32.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/jenkins_home

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: dev
  labels:
    app: jenkins

spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: cluster
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins